yev/pdf data quality report
gretelai/navigator-helpers pull request #41
Opened 2024-10-17 21:40 UTC by 3mei

2024-10-21 15:48 UTC, nina-xu requested changes
Thanks Yev! The main theme around my comments is the different handling for different column data types

2024-10-21 15:48 UTC, nina-xu commented on navigator_helpers/tasks/evaluation/create_pdf_report.ipynb
> +    "    if 'feature_distribution' in data and 'distribution' in data['feature_distribution']:\n",
Note that feature distribution is calculated differently (see [here](https://github.com/gretelai/navigator-helpers/blob/f18f2073f77050c1faec0aee701787084f4449e2/navigator_helpers/tasks/evaluation/evaluation.py#L47)) depending on the data type of the column. It's great to use Pareto charts for categorical columns, however, for text columns, where we calculate the word count, I don't think Pareto charts are appropriate. We can either skip the plotting here, or plot the word counts of all text columns in one plot (you have a similar one down below so i'll leave more specific comments there). Similarly for numeric column types, which we don't have in this dataset.

2024-10-21 15:48 UTC, nina-xu commented on navigator_helpers/tasks/evaluation/create_pdf_report.ipynb
> +    "        dtype = str(dataset_df[col].dtype)\n",
I suggest that we use the column data types determined [here](https://github.com/gretelai/navigator-helpers/blob/f18f2073f77050c1faec0aee701787084f4449e2/navigator_helpers/tasks/evaluation/evaluation.py#L47) (same as my comment on the distribution plots). The same suggestion goes towards the column counts in the "Dataset Overview" table above

2024-10-21 15:48 UTC, nina-xu commented on navigator_helpers/tasks/evaluation/create_pdf_report.ipynb
> +    "    story.append(Paragraph(\"• Gini-Simpson Index: probability that two randomly selected entities from the dataset will be different, with higher values indicating greater diversity.\", styles[
Suggested edit:
Gini-Simpson Index: average diversity index across all categorical fields, defined as the probability that two randomly selected categories from the field will be different, with higher values indicating greater diversity.

(I think there's another description down below where we should similarly point out that this is only for categorical fields)

2024-10-21 15:48 UTC, nina-xu commented on navigator_helpers/tasks/evaluation/create_pdf_report.ipynb
> +    "        word_count = pd.DataFrame.from_dict(data['num_words_per_record']['word_counts_per_column'], orient='index', columns=['avg_words'])\n",
We do have both the average and standard deviation of word counts calculated out of the feature distribution, but only for text columns. Something to consider when plotting this. We can do an average as a dot and std as the error bar.

2024-10-21 15:48 UTC, nina-xu commented on navigator_helpers/tasks/evaluation/create_pdf_report.ipynb
> +    "        story.append(Paragraph(\"• Low cardinality features (e.g., 'sql_complexity' and 'sql_complexity_description' with 8 unique values each) typically represent broader categories or classifi
Thoughts on adjusting this according to the specific field names and size of each dataset?

2024-11-07 15:21 UTC, 3mei commented
Closing this out with parity to Jarvis.

2024-11-07 15:22 UTC, merged